version: '3.3'

services:
  # Database
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data3:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '33060:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_DATABASE : heyDjBase 
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8282:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['www:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
  #heyDjServer
  heydj_web:
    build: 
       context: nodeDockeration
       dockerfile: Dockerfile
    depends_on:
      - db
    environment:
    - APP_PORT=8181
    - APP_MYSQL_PORT= 3306
    - APP_MYSQL_USER= root
    - APP_MYSQL_PWD= password
    - APP_MYSQL_IP=  db
    image: navyblu971/hey-dj-server:v5
    ports:
     - "8181:8181"
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data3:
  www: